name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run test

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - run: echo "@chiff-app:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Set version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm version --preid=ci-$GITHUB_RUN_ID --no-git-tag-version prerelease
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
